apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat  # Use a fixed name instead of using `{{ include "tomcat.fullname" . }}`
  labels:
    app: tomcat  # You can also just use the name directly here.
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
