apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ng-app
  name: ng-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ng-app
  template:
    metadata:
      labels:
        app: ng-app
    spec:
      containers:
        - image: nginx:1.27.3
          name: ng-app
