apiVersion: v1
kind: Service
metadata:
  name: {{ include "tomcat-chart.fullname" . }}
  labels:
    {{- include "tomcat-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "tomcat-chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
